version: 2.1

orbs:
  python: circleci/python@3.10

jobs:
  install_deps:
    steps:
      - checkout
      - pip install .[dev]
  test:
    steps:
      - run:
          command: tox -e $TOX_ENV

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  run_tests:
    jobs:
      - install_deps
      - test
